language: node_js

node_js:
  - stable

services:
  - mysql

cache:
  directories:
    - node_modules

before_install:
  - mysql -e 'CREATE DATABASE sms_management_api_test;'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 >
    ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run db:rollmigrate
  - yarn run build
  - yarn test:coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
